name: Docker Image CI

on:
  push:
    branches: [ "*" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push to local registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: giuseppelillo/aiven:latest
          cache-from: type=registry,ref=giuseppelillo/aiven:latest
          cache-to: type=inline
      -
        name: Inspect
        env:
          LOG_LEVEL: ${{ secrets.CA_CERTIFICATE }}
        run: |
          docker run giuseppelillo/aiven:latest

#jobs:
#
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v3
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag aiven:$(date +%s)
