name: Test file bas64

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.CA_CERTIFICATE }}
        run: |
          echo "$SUPER_SECRET"